### ISSUE TITLE
{"message":"This resource requires authentication"}

### ISSUE THREAD

**Issue by hepin1989** [softprops/bintray-sbt#66]
I have setup the api key,but always this message shows up.

**Comment by alexander-myltsev** [comment]
Same for me :(

**Comment by cppexpert** [comment]
Yeah, I think the plugin is simply broken.

**Comment by 2m** [comment]
It works fine here. I have released today a simple library and an sbt plugin without any problems. What is the full error message that you are seeing?

**Comment by cppexpert** [comment]
There are at least 15 other people here and in other issues with same problem. Here is full call-stack I get

```
> publish
[info] Wrote C:\work\sideprojects\medstream\medstream-models\target\medstream-models-1.2.pom
[info] :: delivering :: co.kernelnetworks#medstream-models;1.2 :: 1.2 :: release :: Sun Jul 26 22:25:42 MSK 2015
[info]  delivering ivy file to C:\work\sideprojects\medstream\medstream-models\target\ivy-1.2.xml
{"message":"This resource requires authentication"}
[trace] Stack trace suppressed: run last *:publish for the full output.
[error] (*:publish) error uploading to https://api.bintray.com/maven/cppexpert/maven/maven/co/kernelnetworks/medstream-models/1.2/medstream-models-1.2.pom: {"message":"This resource requires authentic
ation"}
[error] Total time: 2 s, completed Jul 26, 2015 10:25:44 PM
> last *:publish
java.lang.RuntimeException: error uploading to https://api.bintray.com/maven/cppexpert/maven/maven/co/kernelnetworks/medstream-models/1.2/medstream-models-1.2.pom: {"message":"This resource requires a
uthentication"}
        at bintray.BintrayMavenRepository.put(Resolver.scala:27)
        at org.apache.ivy.plugins.resolver.RepositoryResolver.put(RepositoryResolver.java:234)
        at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
        at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:336)
        at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:335)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
        at sbt.IvyActions$.publish(IvyActions.scala:335)
        at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply$mcV$sp(IvyActions.scala:121)
        at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply(IvyActions.scala:121)
        at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply(IvyActions.scala:121)
        at sbt.IvyActions$.withChecksums(IvyActions.scala:130)
        at sbt.IvyActions$.sbt$IvyActions$$withChecksums(IvyActions.scala:125)
        at sbt.IvyActions$$anonfun$publish$1.apply(IvyActions.scala:121)
        at sbt.IvyActions$$anonfun$publish$1.apply(IvyActions.scala:114)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:127)
        at sbt.IvySbt.withIvy(Ivy.scala:124)
        at sbt.IvySbt$Module.withModule(Ivy.scala:155)
        at sbt.IvyActions$.publish(IvyActions.scala:114)
        at sbt.Classpaths$$anonfun$publishTask$1.apply(Defaults.scala:1283)
        at sbt.Classpaths$$anonfun$publishTask$1.apply(Defaults.scala:1282)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:publish) error uploading to https://api.bintray.com/maven/cppexpert/maven/maven/co/kernelnetworks/medstream-models/1.2/medstream-models-1.2.pom: {"message":"This resource requires authentic
ation"}
```

**Comment by 2m** [comment]
I get this message when I set my bintray credentials to something invalid. Are you sure your bintray credentials are set fine (username and API key, not password)?

**Comment by cppexpert** [comment]
Yep, just re-tested to be sure.

**Comment by cppexpert** [comment]
I think that was it, @2m. Thank you for pointing out. I was sure I used API key but perhaps I didn't.

**Comment by hepin1989** [comment]
@2m I am using the right API key ,just copy & paste from the webpage

**Comment by 2m** [comment]
Where are you deploying to? Is it an organization repo?

**Comment by hepin1989** [comment]
It's myself jcenter repo.I will take another look at this later.

**Comment by softprops** [comment]
Note, you don't typically publish directly to jcenter. You publish to your (username)/maven repository and then [link it to the jcenter repo](https://bintray.com/docs/usermanual/uploads/uploads_includingyourpackagesinjcenter.html). After the link gets approved it you should be able to have publish new versions to you (username)/maven repository and have it transparently mirrored on jcenter

**Comment by hepin1989** [comment]
infact this is an user error.
I will update the readme

**Comment by zy1301529626** [comment]
Could not create package 'heyzhuyue/maven/shopcartlib': HTTP/1.1 401 Unauthorized [message:This resource requires authentication]

**Comment by PhilAndrew** [comment]
I think in general most people are putting in their bintray password rather than the API key, where it says to put password because it literally says password.

realm = Bintray API Realm
host = api.bintray.com
user = myuser
password = mypassword should be the api key here

**Comment by avdv** [comment]
Hi. Just an anecdotal note since I also received the error message from the API although the `bintrayEnsureCredentials` task run successfully beforehand...

The problem was that I hid the `BINTRAY_USER` environment variable on Travis CI, which redacted its value inside the job -- but it also redacted the value inside the bintray URL and replaced it with `[secure]`.

So, make sure to enable the "Display value in build log" checkbox for the user, but not for the password variable!
